// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo0OTCqp3d4LIbZEoLTORa2jOe2C19FRA',
    appId: '1:593966857248:web:680a7098073af20390d045',
    messagingSenderId: '593966857248',
    projectId: 'pokedex-api-102a9',
    authDomain: 'pokedex-api-102a9.firebaseapp.com',
    storageBucket: 'pokedex-api-102a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABOeHX4P-f5oNiobOjidntfJu0lSwEQ4g',
    appId: '1:593966857248:android:4fb2ca8c83c2c74890d045',
    messagingSenderId: '593966857248',
    projectId: 'pokedex-api-102a9',
    storageBucket: 'pokedex-api-102a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmZu4WHxOKUwgOqtGUGFek_22277QQIk',
    appId: '1:593966857248:ios:8d52ca6d225fe8a090d045',
    messagingSenderId: '593966857248',
    projectId: 'pokedex-api-102a9',
    storageBucket: 'pokedex-api-102a9.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmZu4WHxOKUwgOqtGUGFek_22277QQIk',
    appId: '1:593966857248:ios:8d52ca6d225fe8a090d045',
    messagingSenderId: '593966857248',
    projectId: 'pokedex-api-102a9',
    storageBucket: 'pokedex-api-102a9.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo0OTCqp3d4LIbZEoLTORa2jOe2C19FRA',
    appId: '1:593966857248:web:8557f67d4c50009290d045',
    messagingSenderId: '593966857248',
    projectId: 'pokedex-api-102a9',
    authDomain: 'pokedex-api-102a9.firebaseapp.com',
    storageBucket: 'pokedex-api-102a9.firebasestorage.app',
  );
}
